# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 08:37
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drf_secure_token', '0003_auto_20151223_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='dead_in',
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AddField(
            model_name='token',
            name='marked_for_delete',
            field=models.BooleanField(default=False),
        ),
    ]
